<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Login successefully executed]]>
    </line>
    <line>
      <![CDATA[<a target= "_blank" href = Fri_Feb_08_00_15_13_EST_2019.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target= "_blank" href = Fri_Feb_08_00_15_13_EST_2019.jpg><img src=Fri_Feb_08_00_15_13_EST_2019.jpg height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[Login successefully executed]]>
    </line>
    <line>
      <![CDATA[<a target= "_blank" href = Fri_Feb_08_00_15_14_EST_2019.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target= "_blank" href = Fri_Feb_08_00_15_14_EST_2019.jpg><img src=Fri_Feb_08_00_15_14_EST_2019.jpg height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite name="Data Driven Basics" duration-ms="4786" started-at="2019-02-08T05:15:09Z" finished-at="2019-02-08T05:15:14Z">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="3876" started-at="2019-02-08T05:15:09Z" finished-at="2019-02-08T05:15:13Z">
      <class name="com.w2a.testcases.BankManagerLoginTest">
        <test-method status="PASS" signature="loginAsBankManager()[pri:0, instance:com.w2a.testcases.BankManagerLoginTest@2e3967ea]" name="loginAsBankManager" duration-ms="3630" started-at="2019-02-08T00:15:09Z" finished-at="2019-02-08T00:15:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.w2a.testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Test" duration-ms="877" started-at="2019-02-08T05:15:13Z" finished-at="2019-02-08T05:15:14Z">
      <class name="com.w2a.testcases.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.w2a.testcases.AddCustomerTest@60099951]" name="setUp" is-config="true" duration-ms="4281" started-at="2019-02-08T00:15:05Z" finished-at="2019-02-08T00:15:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="addCustomerTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.testcases.AddCustomerTest@60099951]" name="addCustomerTest" duration-ms="1" started-at="2019-02-08T00:15:13Z" data-provider="dp" finished-at="2019-02-08T00:15:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mohammed]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sahan]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[10462.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing Test Case]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing Test Case
	at org.testng.Assert.fail(Assert.java:93)
	at com.w2a.testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Login successefully executed]]>
            </line>
            <line>
              <![CDATA[<a target= "_blank" href = Fri_Feb_08_00_15_13_EST_2019.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target= "_blank" href = Fri_Feb_08_00_15_13_EST_2019.jpg><img src=Fri_Feb_08_00_15_13_EST_2019.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="FAIL" signature="addCustomerTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.testcases.AddCustomerTest@60099951]" name="addCustomerTest" duration-ms="1" started-at="2019-02-08T00:15:14Z" data-provider="dp" finished-at="2019-02-08T00:15:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[farah]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[rashid]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[10463.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing Test Case]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing Test Case
	at org.testng.Assert.fail(Assert.java:93)
	at com.w2a.testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Login successefully executed]]>
            </line>
            <line>
              <![CDATA[<a target= "_blank" href = Fri_Feb_08_00_15_14_EST_2019.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target= "_blank" href = Fri_Feb_08_00_15_14_EST_2019.jpg><img src=Fri_Feb_08_00_15_14_EST_2019.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.w2a.testcases.AddCustomerTest@60099951]" name="tearDown" is-config="true" duration-ms="3101" started-at="2019-02-08T00:15:14Z" finished-at="2019-02-08T00:15:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.w2a.testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Data Driven Basics -->
</testng-results>
